# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Documents\PROYECT\PharmacyProject\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(562, 611)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 50, 141, 61))
        self.label.setStyleSheet("color: rgb(231, 231, 231);font-size:28pt;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 210, 81, 21))
        self.label_2.setStyleSheet("font-size:15pt;\n"
"color:rgb(255, 0, 127)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 290, 121, 21))
        self.label_3.setStyleSheet("font-size:15pt;\n"
"color: rgb(255, 0, 127)")
        self.label_3.setObjectName("label_3")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(200, 200, 281, 31))
        self.email.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.email.setText("")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(200, 280, 281, 31))
        self.password.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.password.setText("")
        self.password.setObjectName("password")
        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(380, 370, 101, 31))
        self.loginbutton.setStyleSheet("background-color: rgb(167, 168, 167);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.loginbutton.setObjectName("loginbutton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(230, 120, 151, 16))
        self.label_4.setObjectName("label_4")
        self.createaccbutton = QtWidgets.QPushButton(Dialog)
        self.createaccbutton.setGeometry(QtCore.QRect(380, 320, 101, 31))
        self.createaccbutton.setStyleSheet("background-color: rgb(167, 168, 167);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.createaccbutton.setObjectName("createaccbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "LOG IN "))
        self.label_2.setText(_translate("Dialog", "Email : "))
        self.label_3.setText(_translate("Dialog", "Password : "))
        self.loginbutton.setText(_translate("Dialog", "LOGIN"))
        self.label_4.setText(_translate("Dialog", "PROYECT BY JARED AND MOU "))
        self.createaccbutton.setText(_translate("Dialog", "CREATE"))
